name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
           login-server: pricingdbnonpacr.azurecr.io
           username: pricingdbnonpacr
           password: 2LcWCt7ZDKBGwUsj4x7mqb+QY57G4Wkw
      - run: |
          docker build . -t pricingdbnonpacr.azurecr.io/pricingdb-ui:${{ github.sha }}
          docker push pricingdbnonpacr.azurecr.io/pricingdb-ui:${{ github.sha }}
      - uses: azure/webapps-deploy@v2
        with:
          app-name: gitaction-poc
          images: pricingdbnonpacr.azurecr.io/pricingdb-ui:${{ github.sha }}